name: 'clean_history_commit'

on:
  workflow_dispatch:
    inputs:
        tags:
          description: 'action'  
  #schedule:
  #  - cron: '00 1 * * *'

permissions: write-all

jobs:
  clean_history_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Clean history
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout --orphan latest_branch
          git add -A
          git commit -am "clean history commit"
          git branch -D main
          git branch -m main
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git push -f origin main


