name: 'cnjbl(y)_last24month'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'

env:
  repo_name: CECNdata/GA-sec
  retry: 3

jobs:
  last24month:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
         - csv: cnjbl.csv
           line: 0
           part: 0
         - csv: cnjbl.csv
           line: 0
           part: 1
         - csv: cnjbl.csv
           line: 0
           part: 2
         - csv: cnjbl.csv
           line: 0
           part: 3
         - csv: cnjbl.csv
           line: 1
           part: 0
         - csv: cnjbl.csv
           line: 1
           part: 1
         - csv: cnjbl.csv
           line: 1
           part: 2
         - csv: cnjbl.csv
           line: 1
           part: 3
         - csv: cnjbly.csv
           line: 0
           part: 0
         - csv: cnjbly.csv
           line: 0
           part: 1
         - csv: cnjbly.csv
           line: 0
           part: 2
         - csv: cnjbly.csv
           line: 0
           part: 3
         - csv: cnjbly.csv
           line: 1
           part: 0
         - csv: cnjbly.csv
           line: 1
           part: 1
         - csv: cnjbly.csv
           line: 1
           part: 2
         - csv: cnjbly.csv
           line: 1
           part: 3

    steps:
      - name: Checkout codes
        uses: actions/checkout@v3
        with:
          repository: '${{ env.repo_name  }}'
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains you PAT
          
      - uses: actions/setup-node@v3
      - name: Install playwright browsers
        run: npx playwright install --with-deps

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          cd customs
          python -m pip install --upgrade pip
          pip install fire
          pip install pipreqs
          pipreqs .
          pip install -r requirements.txt

      - name: Install Playwright
        run: |
            python -m playwright install
      - name: run customs download
        continue-on-error: true
        run: |
            cd customs
            timeout 1800 xvfb-run python run_24m.py  --path mapping/${{matrix.csv}} --line "${{matrix.line}}" --retry ${{env.retry}} --part ${{matrix.part}}
