name: 'cnjbl(y)_optional'

on:
  workflow_dispatch:
    inputs:
      start_date:
        description: 'start_date'
        required: false
        default: "202101"
      end_date:
        description: 'end_date'
        required: false
        default: "202201"
      timeout:
        description: 'timeout'
        required: false
        default: "1800"
env:
  start_date: ${{ github.event.inputs.start_date }}
  end_date: ${{ github.event.inputs.end_date }}
  repo_name: CECNdata/GA-sec
  retry: 3
  timeout: ${{ github.event.inputs.timeout}}


jobs:
  shell:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
         - csv: cnjbl.csv
           line: 0
         - csv: cnjbl.csv
           line: 1
         - csv: cnjbly.csv
           line: 0
         - csv: cnjbly.csv
           line: 1

    steps:
      - name: Checkout codes
        uses: actions/checkout@v3
        with:
          repository: '${{ env.repo_name  }}'
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains you PAT

      - uses: actions/setup-node@v3
      - name: Install playwright browsers
        run: npx playwright install --with-deps

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          cd customs
          python -m pip install --upgrade pip
          pip install fire
          pip install pipreqs
          pipreqs .
          pip install -r requirements.txt

      - name: Install Playwright
        run: |
            python -m playwright install

      - name: run customs download
        continue-on-error: true
        run: |
            cd customs
            timeout $timeout python download_pyscript/run_optional.py  --path mapping/${{matrix.csv}} --line "${{matrix.line}}" --retry ${{env.retry}}
