name: 'md5_clean'

on:
  workflow_dispatch:
    inputs:
        tags:
          description: 'action'  

jobs:
  shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          wget https://raw.githubusercontent.com/Eloco/Script-collect/main/function/clean_md5_action.py
          python -m pip install --upgrade pip
          pip install fire

      - name: run clean_md5_action
        run: |
            python clean_md5_action.py

      - name: Commit report
        run: |
          git add -A
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "Automated clean md5"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git push -f
